
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LMA.java
 *
 * Created on 24/04/2013, 20:52:25
 */

/**
 *
 * @author Administrador
 */
public class LMA extends javax.swing.JFrame {

    /** Creates new form LMA */
    public LMA() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoPedido = new javax.swing.ButtonGroup();
        frameDetalle = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDetalle = new javax.swing.JTextArea();
        jbtCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jrbCompleto = new javax.swing.JRadioButton();
        jrbSandwich = new javax.swing.JRadioButton();
        jrbPizza = new javax.swing.JRadioButton();
        jcbTamano = new javax.swing.JComboBox();
        jcbBeber = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtCalcular = new javax.swing.JButton();
        jbtImprimir = new javax.swing.JButton();
        jbtBorrar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jchMayo = new javax.swing.JCheckBox();
        jchKetchup = new javax.swing.JCheckBox();
        jchMostaza = new javax.swing.JCheckBox();
        jchAmericana = new javax.swing.JCheckBox();
        jchTomate = new javax.swing.JCheckBox();
        jchPalta = new javax.swing.JCheckBox();
        jchChucrut = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jchExtraQueso = new javax.swing.JCheckBox();
        jchCarne = new javax.swing.JCheckBox();
        jchChoricillos = new javax.swing.JCheckBox();
        jchChoclos = new javax.swing.JCheckBox();
        jchPalmitos = new javax.swing.JCheckBox();
        jchEsparrago = new javax.swing.JCheckBox();

        jtaDetalle.setColumns(20);
        jtaDetalle.setRows(5);
        jScrollPane1.setViewportView(jtaDetalle);

        jbtCerrar.setText("Cerrar");

        javax.swing.GroupLayout frameDetalleLayout = new javax.swing.GroupLayout(frameDetalle.getContentPane());
        frameDetalle.getContentPane().setLayout(frameDetalleLayout);
        frameDetalleLayout.setHorizontalGroup(
            frameDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameDetalleLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameDetalleLayout.createSequentialGroup()
                        .addComponent(jbtCerrar)
                        .addGap(32, 32, 32))))
        );
        frameDetalleLayout.setVerticalGroup(
            frameDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jbtCerrar)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Mandíbula Atómica");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pedido"));

        grupoTipoPedido.add(jrbCompleto);
        jrbCompleto.setText("Completo");
        jrbCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCompletoActionPerformed(evt);
            }
        });

        grupoTipoPedido.add(jrbSandwich);
        jrbSandwich.setText("Sándwich");
        jrbSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSandwichActionPerformed(evt);
            }
        });

        grupoTipoPedido.add(jrbPizza);
        jrbPizza.setText("Pizza");
        jrbPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbCompleto)
                    .addComponent(jrbPizza)
                    .addComponent(jrbSandwich))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jrbCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbSandwich)
                .addGap(3, 3, 3)
                .addComponent(jrbPizza)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jcbTamano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Chico", "Mediano", "Grande" }));

        jcbBeber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Nada>", "Bebida Lata", "Jugo Natural", "Café", "Té" }));

        jLabel1.setText("Tamaño");

        jLabel2.setText("Para Beber");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        jbtCalcular.setText("Calcular");
        jbtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularActionPerformed(evt);
            }
        });

        jbtImprimir.setText("Imprimir");
        jbtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimirActionPerformed(evt);
            }
        });

        jbtBorrar.setText("Borrar");
        jbtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBorrarActionPerformed(evt);
            }
        });

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbtCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSalir)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados C/S"));

        jchMayo.setText("Mayo");
        jchMayo.setEnabled(false);
        jchMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchMayoActionPerformed(evt);
            }
        });

        jchKetchup.setText("Ketchup");
        jchKetchup.setEnabled(false);
        jchKetchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchKetchupActionPerformed(evt);
            }
        });

        jchMostaza.setText("Mostaza");
        jchMostaza.setEnabled(false);
        jchMostaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchMostazaActionPerformed(evt);
            }
        });

        jchAmericana.setText("Americana");
        jchAmericana.setEnabled(false);
        jchAmericana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchAmericanaActionPerformed(evt);
            }
        });

        jchTomate.setText("Tomate");
        jchTomate.setEnabled(false);
        jchTomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchTomateActionPerformed(evt);
            }
        });

        jchPalta.setText("Palta");
        jchPalta.setEnabled(false);
        jchPalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchPaltaActionPerformed(evt);
            }
        });

        jchChucrut.setText("Chucrut");
        jchChucrut.setEnabled(false);
        jchChucrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchChucrutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchMayo)
                    .addComponent(jchKetchup)
                    .addComponent(jchMostaza)
                    .addComponent(jchPalta)
                    .addComponent(jchTomate)
                    .addComponent(jchAmericana)
                    .addComponent(jchChucrut))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jchMayo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchKetchup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchMostaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchAmericana)
                .addGap(3, 3, 3)
                .addComponent(jchTomate)
                .addGap(3, 3, 3)
                .addComponent(jchPalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchChucrut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados Pizza"));

        jchExtraQueso.setText("Extra Queso");
        jchExtraQueso.setEnabled(false);

        jchCarne.setText("Carne");
        jchCarne.setEnabled(false);

        jchChoricillos.setText("Choricillos");
        jchChoricillos.setEnabled(false);

        jchChoclos.setText("Choclos");
        jchChoclos.setEnabled(false);

        jchPalmitos.setText("Palmitos");
        jchPalmitos.setEnabled(false);

        jchEsparrago.setText("Esparragos");
        jchEsparrago.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchExtraQueso)
                    .addComponent(jchCarne)
                    .addComponent(jchChoricillos)
                    .addComponent(jchEsparrago)
                    .addComponent(jchPalmitos)
                    .addComponent(jchChoclos))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jchExtraQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchCarne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchChoricillos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchChoclos)
                .addGap(3, 3, 3)
                .addComponent(jchPalmitos)
                .addGap(3, 3, 3)
                .addComponent(jchEsparrago)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jcbBeber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbBeber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCompletoActionPerformed
        // TODO add your handling code here:
        habilitaPanel(true);
    }//GEN-LAST:event_jrbCompletoActionPerformed

    private void jrbSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSandwichActionPerformed
        // TODO add your handling code here:
        habilitaPanel(true);
    }//GEN-LAST:event_jrbSandwichActionPerformed

    private void jrbPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPizzaActionPerformed
        // TODO add your handling code here:
        habilitaPanel(false);
    }//GEN-LAST:event_jrbPizzaActionPerformed

    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularActionPerformed
        // TODO add your handling code here:
        calcularPedido();
    }//GEN-LAST:event_jbtCalcularActionPerformed

    private void jbtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimirActionPerformed
        // TODO add your handling code here:
        calcularPedido();
        frameDetalle.setVisible(true);
        frameDetalle.pack();
        frameDetalle.setLocationRelativeTo(this);

    }//GEN-LAST:event_jbtImprimirActionPerformed

    private void jbtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBorrarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jchMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchMayoActionPerformed
        // TODO add your handling code here:
       
              
            
            
    }//GEN-LAST:event_jchMayoActionPerformed

    private void jchKetchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchKetchupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchKetchupActionPerformed

    private void jchMostazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchMostazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchMostazaActionPerformed

    private void jchAmericanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchAmericanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchAmericanaActionPerformed

    private void jchTomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchTomateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchTomateActionPerformed

    private void jchPaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchPaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchPaltaActionPerformed

    private void jchChucrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchChucrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchChucrutActionPerformed

    public void habilitaPanel(boolean estado)
    {
        int cComPanel3=jPanel3.getComponentCount();
        int x;
        for (x=0;x<cComPanel3;x++)
        {
            jPanel3.getComponent(x).setEnabled(estado);
        }
        int cComPanel4=jPanel4.getComponentCount();
        for (x=0;x<cComPanel4;x++)
        {
            jPanel4.getComponent(x).setEnabled(!estado);
        }
    }

    public void calcularPedido()
    {
        int aPagar=0;
        String detalle="";
        // 1ro se verifica que tipo de pedido solicitó
        if (jrbCompleto.isSelected())
        {
            aPagar+=500; // aPagar=aPagar+500;
            detalle+="Completo\n";
        }
        else
        {
            if (jrbSandwich.isSelected())
            {
                aPagar+=700;
            }
            else
            {
                if (jrbPizza.isSelected())
                {
                    aPagar+=800;
                }
            }
        }
        // 2do Verificar el tamaño
        int indiceTamano=jcbTamano.getSelectedIndex();
        switch (indiceTamano)
        {
            case 1: // chico
                    aPagar+=0;
                    break;
            case 2: // mediano
                    aPagar+=200;
                    detalle+="Mediano\n";
                    break;
            case 3: // grande
                    aPagar+=400;
                    break;
        }
        // 3ro verificar lo que va a beber
        int indiceBeber=jcbBeber.getSelectedIndex();
        switch (indiceBeber)
        {
            case 1: // bebida lata
                    aPagar+=500;
                    detalle+="Bebida Lata\n";
                    break;
            case 2: // jugo natural
                    aPagar+=600;
                    break;
            case 3: // Cafe
                    aPagar+=400;
                    break;
            case 4: // Te
                    aPagar+=300;
                    break;
        }
        // 4to LOS AGREGADOS
        jtaDetalle.setText(detalle);
        JOptionPane.showMessageDialog(null,"A Pagar: $ "+aPagar);

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame frameDetalle;
    private javax.swing.ButtonGroup grupoTipoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBorrar;
    private javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtCerrar;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox jcbBeber;
    private javax.swing.JComboBox jcbTamano;
    private javax.swing.JCheckBox jchAmericana;
    private javax.swing.JCheckBox jchCarne;
    private javax.swing.JCheckBox jchChoclos;
    private javax.swing.JCheckBox jchChoricillos;
    private javax.swing.JCheckBox jchChucrut;
    private javax.swing.JCheckBox jchEsparrago;
    private javax.swing.JCheckBox jchExtraQueso;
    private javax.swing.JCheckBox jchKetchup;
    private javax.swing.JCheckBox jchMayo;
    private javax.swing.JCheckBox jchMostaza;
    private javax.swing.JCheckBox jchPalmitos;
    private javax.swing.JCheckBox jchPalta;
    private javax.swing.JCheckBox jchTomate;
    private javax.swing.JRadioButton jrbCompleto;
    private javax.swing.JRadioButton jrbPizza;
    private javax.swing.JRadioButton jrbSandwich;
    private javax.swing.JTextArea jtaDetalle;
    // End of variables declaration//GEN-END:variables

}
